/* Generated by tools/build_content.py -- do not edit by hand. */
#ifndef CONTENT_H
#define CONTENT_H

#include <stdint.h>

/* First byte of every display line is its style: */
#define STYLE_BODY    '0'
#define STYLE_HEAD    '1'
#define STYLE_FORM    '2'
#define STYLE_BULLET  '3'
#define BULLET_CONT   '\x01'  /* wrapped continuation of a bullet */

#define WIKI_TITLE "MATHWIKI"
#define WIKI_COLS 37
#define WIKI_MAX_LINES 43  /* longest article, for the runtime line index */

typedef struct {
    const char *title;
    const char *body;      /* newline-separated, style-prefixed lines */
    uint16_t    num_lines;
} article_t;

typedef struct {
    const char     *title;
    const article_t *articles;
    uint8_t         num_articles;
} category_t;

typedef struct {
    uint8_t cat;
    uint8_t art;
} artref_t;

extern const category_t wiki_categories[];
extern const uint8_t    wiki_num_categories;
extern const artref_t   wiki_index[];   /* all articles, sorted by title */
extern const uint16_t   wiki_index_size;

#endif
